// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixzuajbcoyrpgphvpvqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4enVhamJjb3lycGdwaHZwdnFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NTI5MTQsImV4cCI6MjA3MDQyODkxNH0.Ku1oORZRE_XYO8F9jNLaxHcc9UJIGWjpnAXuq7pEac0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});